baseURL = "https://hyeamykim.github.io/" 
languageCode = "en"
theme = "anatole"
enableEmoji = true

[params] 
author = "hyeamykim" 
title = "My blog"
description = "Showcasing My Project-based-learning" 
authorEmail = "hyeamykim@gmail.com"
profilePicture = "images/profile_photo.jpg"  


